### ISSUE TITLE
luna/osimage.py now requires pigz

### ISSUE THREAD

**Issue by Marc69** [clustervision/luna#36]
, which is not supplied when luna has been git cloned. Trivial, but it took a lot of time to find out, so may this serve as a warning!
**Version: ** 3d8e6d4

**Comment by dchirikov** [comment]
We have it as a requirement in RPM:
https://github.com/clustervision/luna/blob/3d8e6d463cf142ef711762d95ae51794a95cce8b/rpm/luna.spec.in#L88
